### ISSUE TITLE
Joining the group

### ISSUE THREAD

**Issue by AayushGrover** [STIMALiU/ml-reading-group#1]
Greetings,

I am Aayush Grover, a final year master in Data Science student from IIIT Bangalore, India. I have been working on machine learning for a few years now. My research interests lie in bridging the gap between state-of-the-art artificial intelligence and molecular biology. You can find more about me [here](https://aayushgrover.github.io/).

Kindly let me know if I can join this group without being associated with Linköping University. 

Many thanks,
Aayush Grover

**Comment by joeloskarsson** [comment]
Hi Aayush,
My guess is that this request is no longer relevant, but I hope that you found some other reading group that you could join. As we now meet in person we can only accommodate people in Linköping.
